const REDIS_EVENT = {
    ERROR: "error"
}

const SOCKET_IO_EVENT = {
    CONNECTION: 'connection',
    CODE_CHANGED: 'CODE_CHANGED',
    CONNECTED_TO_ROOM: 'CONNECTED_TO_ROOM',
    ROOM_CONNECTION: 'ROOM:CONNECTION',
    ROOM_DISCONNECT: 'ROOM:DISCONNECT',
    DISCONNECT: 'disconnect',
    DB_ERROR: 'DB_ERROR',
    CODE_INSERT: "CODE_INSERT",
    CODE_REPLACE: "CODE_REPLACE",
    CODE_DELETE: "CODE_DELETE",
    OUTPUT_CHANGED: "OUTPUT_CHANGED",
    CURSOR_CHANGED: 'CURSOR_CHANGED',
    SELECTION_CHANGED: 'SELECTION_CHANGED',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
    CHANGE_VERSION: 'CHANGE_VERSION'
}

module.exports = REDIS_EVENT
module.exports = SOCKET_IO_EVENT