const REDIS_EVENT = {
    ERROR: "error"
}

const SOCKET_IO_EVENT = {
    CONNECT: 'connection',
    CODE_CHANGED: 'CODE_CHANGED',
    CONNECTED_TO_ROOM: 'CONNECTED_TO_ROOM',
    ROOM_CONNECTION: 'ROOM:CONNECTION',
    DISCONNECT: 'disconnect',
    ERROR: 'error',
    CODE_INSERT: "CODE_INSERT",
    CODE_REPLACE: "CODE_REPLACE",
    CODE_DELETE: "CODE_DELETE",
    OUTPUT_CHANGED: "OUTPUT_CHANGED",
    CURSOR_CHANGED: 'CURSOR_CHANGED',
    SELECTION_CHANGED: 'SELECTION_CHANGED'
}

module.exports = REDIS_EVENT
module.exports = SOCKET_IO_EVENT